<h3><b>Introduction to Data Analytics - Exercise set 5 - data processing and management</b></h3>

Put all your exercises (Jupyter Notebooks or Python-files) in your course Git-project.<br /><br />
<span style="font-weight: bold;">Use either code comments or Jupyter Notebook markdown (text) to document which exercise you are doing and what a certain code section does!</span><br />

<span style="font-weight: bold;">Remember: your Jupyter notebook's clarity (how easy it is to read and understand) also affects your scoring!</span><br /><br />
<span style="font-weight: bold;">Remember also: 
<span style="font-weight: bold;">If you use generative AI in any part of any exercise, 
MENTION IT CLEARLY! </span><br />
<span style="font-weight: bold;">(code comments are enough, also mention the prompts used).</span><br /><br />
See also the materials discussing the usage of AI in this course!</span><br /><br />


You can return all of these exercises in a single Jupyter Notebook, if you wish.

<p style="color: red;"><b>NOTE: The JSON/XML –files in Moodle in these exercises have been randomly generated. In other words, the data doesn't make any sense!</b></p>

In [70]:
# importing the common data analytics modules for the exercise
import numpy as np
import pandas as pd
import seaborn as sns
import xml.etree.ElementTree as et
import json
import requests
from bs4 import BeautifulSoup

<h4><b>1. </b>Download <b>"simple.json"</b> in Moodle, and load it in pandas.</b> </h4>
<p>
The DataFrame should look like this:
</p>

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex51.png" width="1000"/>

In [71]:
df = pd.read_json('simple.json')
df.head(5)

,id,brand,model,year,owned_by,acquired,price
0,1,Chrysler,Voyager,2001,Wolff-Trantow,28/12/2016,11565
1,2,Volkswagen,Jetta,1995,"Schuppe, Pfeffer and Klein",20/4/2016,52431
2,3,Porsche,Cayenne,2005,Mante Group,11/6/2020,75552
3,4,Porsche,928,1994,Wisozk Group,17/6/2019,30331
4,5,Mercedes-Benz,SL-Class,2007,Schiller-Littel,20/7/2018,62385

<h4><b>2.</b> Download <b>"simple.xml"</b> in Moodle, and load it in pandas</h4>
<p>
<span style="color: red"><b>(Note:</b> if using pandas.read_xml(), use also the xpath-parameter!)</span><br /><br >The Series should look something like this:
</p>

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex52.png" />

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex52cars.jpg" width="600" />

In [72]:
# Using pandas.read_xml(), also using the xpath-parameter

df = pd.read_xml("simple.xml", xpath="/*")
df

   id       brand   model  year                    owned_by    acquired  price
0   1  Oldsmobile  Aurora  2003  Herzog, Rodriguez and Howe  21/10/2016  32571

## Note: Opettaja i have also tried this with in a  different way let me if it is useful or not as the file only have line of data but i tried to understand try something new!

In [73]:

import xml.etree.ElementTree as et

# load XML-file -> get root node
xtree = et.parse("simple.xml")
node = xtree.getroot()

# column names for pandas when we create the final DataFrame
df_cols = ["id", "brand", "model", "year", "owned_by", "acquired", "price"]
rows = []

# parse "columns" or values in the XML
e_id = node.find("id").text
e_brand = node.find("brand").text
e_model = node.find("model").text
e_year = node.find("year").text
e_owned_by = node.find("owned_by").text
e_acquired = node.find("acquired").text
e_price = node.find("price").text


# create the DataFrame
rows.append({'id': e_id, 'brand': e_brand, 'model': e_model, 'year': e_year, 'owned_by': e_owned_by, 'acquired': e_acquired, 'price': e_price})
out_df = pd.DataFrame(rows, columns=df_cols)

# printing out_df
out_df

  id       brand   model  year                    owned_by    acquired  price
0  1  Oldsmobile  Aurora  2003  Herzog, Rodriguez and Howe  21/10/2016  32571

<h4><b>3. Load this API-data into a pandas DataFrame:</b></h4>
<p><a href="https://edu.frostbit.fi/api/events/en">https://edu.frostbit.fi/api/events/en</a></p>

<p>
Remember to use json_normalize to help you out with the categories and address information.<br /><b>Have address information in their own columns, and categories as separate rows.</b><br />The DataFrame should look something like this (note that the data changes daily, and exact values will vary):


</p>

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex53.png"/>

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex53events.jpg" width="600" />

In [74]:
# defining the URL.
url = "https://edu.frostbit.fi/api/events/en"
page = requests.get(url)

json_page = page.json()
data = pd.json_normalize(json_page)
data = data.drop('categories', axis=1)

# printing the data variable
data

,name,date,address.street_address,address.postal_code
0,Basketball tournament,10.6.2025,Salpausseläntie 1,00710
1,Herman Brothers in Valimo,30.5.2025,"Suomenlinna B 13, Suomenlinnan vierasvenesatama",00190
2,English Chat Club,6.5.2025,Kirkonkyläntie 2,00700
3,Guided Walking Tour at Suomenlinna in English,1.6.2025,Suomenlinna C 74,00190
4,Park football tournament,16.6.2025,Jengipolku 8,00710
5,KOOLA's spring art fair,25.5.2025,Pengerkatu 9,00530
6,DJ Old Crank in Valimo,6.6.2025,"Suomenlinna B 13, Suomenlinnan vierasvenesatama",00190
7,"Vishnu Vardhani Rajan, Zwoisy Mears Clarke & K...",23.5.2025,Lintulahdenkatu 3,00530
8,Basketball tournament,10.6.2025,Salpausseläntie 1,00710
9,"Vishnu Vardhani Rajan, Zwoisy Mears Clarke & K...",23.5.2025,Lintulahdenkatu 3,00530
10,Narcisa -contemporary ballet,21.5.2025,Bulevardi 27,00180
11,Price of Peace: Group Exhibition of HIAA members,6.5.2025,Myllykallionrinne 1,00200
12,Ateljee - Lallukka Visual Artists' Celebration...,2.5.2025,Apollonkatu 13,00100
13,Vårvind - Kevadtuul,14.5.2025,Minervankatu 6,00100

<h4><b>4. Use web scraping (e.g. BeautifulSoup), and use it to get the following info from the Rovaniemi Wikipedia –page</b></h4>
<p><b>Wiki-page:</b> <a href="https://en.wikipedia.org/wiki/Rovaniemi">https://en.wikipedia.org/wiki/Rovaniemi</a></p>

<b>Tasks:</b>
<ul>
    <li>Get the coordinates of Rovaniemi (upper right corner)</li>
    <li>Get the nickname of Rovaniemi (under coat of arms)</li>
</ul>

<b>Advanced extra tasks:</b>
<ul>
    <li><b>Get the total population</b></li>
    <ul>
        <li><b>Note:</b> this is a good example why webscraping can be tedious, since you'll have to traverse the HTML-tree to get what you want. This might be helpful:<br />
<a href="https://realpython.com/beautiful-soup-web-scraper-python/">https://realpython.com/beautiful-soup-web-scraper-python/</a></li>
    </ul>
    
</ul>

<ul>
    <li><b>Get the total area</b></li>
    <ul>
        <li>Convert this number into a float decimal (i.e. remove commas and the unit and call float() –in Python!)</li>
    </ul>
    
</ul>

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex54rovaniemi.jpg" width="600" />

In [75]:
url = "https://en.wikipedia.org/wiki/Rovaniemi"
page = requests.get(url)

In [ ]:
# soup = BeautifulSoup(page.content, 'html.parser')

In [77]:
# Getting the coordinates of Rovaniemi (upper right corner)
coordinates_latitude = soup.find("span", class_="latitude").text
coordinates_longitude = soup.find("span", class_="longitude").text

coordinates = coordinates_latitude + coordinates_longitude
# printing final coordinates with both latitude and longitude
print("Coordinates:", coordinates)

Coordinates: 66°30′N025°44′E

In [78]:
# Get the nickname of Rovaniemi (under coat of arms
nickname = soup.find("div", class_="ib-settlement-nickname nickname").text

# printing the nickname
print(nickname)

Arctic Capital; Hometown of Santa Claus[1]

<h2><b style="color: red;">Co-operate with another student: Jeremy  </b></h2>

In [79]:
# Instead of using find (which finds the very first instance)
# Let's use find-all
Total_population = soup.find_all("td", class_="infobox-data")[10].text
print('Total population:', Total_population)

Total population: 65,881

In [ ]:
# Getting the total area .a     
Total_area = soup.find_all("td", class_="infobox-data")[6].text
Total_area


# Converting this number into a float decimal 
# (i.e. remove commas and the unit and call float() –in Python!)
float_number = float(Total_area.replace(",", "").split()[0])
print(float_number)

8016.75

<h4><b>5. Use web scraping, and create a DataFrame of this table: </b></h4>
<p> <a href="https://en.wikipedia.org/wiki/List_of_countries_by_average_yearly_temperature">https://en.wikipedia.org/wiki/List_of_countries_by_average_yearly_temperature</a></p>

<ul>
    <li>Change the name of the value column to "avg_temp" as well (pandas column rename)</li>
</ul>
<ul>
    <li><b>Small extra task: </b>clean up the column so that only the 
numeric °C-value is present (no other characters)
</li>
</ul>

<b>Advanced extra task:</b>
<ul>
    <li><b>Scrape these two tables as well</b></li>
    <ul>
        <li><a href="https://en.wikipedia.org/wiki/List_of_countries_by_employment_rate">https://en.wikipedia.org/wiki/List_of_countries_by_employment_rate</a></li>
        <li><a href="https://en.wikipedia.org/wiki/List_of_countries_by_unemployment_rate">https://en.wikipedia.org/wiki/List_of_countries_by_unemployment_rate</a></li>
    </ul>
    <br />
    <ul>
        <li><b>Combine the tables into a single DataFrame so that you get only the data of year 2020 or newer, and have the columns <span style="color: darkorange">"Country", "EmploymentRate"</span> and <span style="color: darkorange">"UnemploymentRate"</span>. You can also create additional columns <span style="color: red">"EmploymentRate15_24"</span>and <span style="color: red">"EmploymentRate25_70"</span> if you scrape the OECD-table as well! </b>

</li>
    </ul>
</ul>

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex55stocks.jpg" width="450" />

In [81]:
# # code here

# # USE THIS TO GET TEH DATA
# # Place the URL here.
# url = "https://en.wikipedia.org/wiki/List_of_best-selling_video_games"

# # Turn the URL into a dataframe.
# data = pd.read_html(url)

# # HTML pages tend to have tables that don't look like tables.
# # adjust the index so that it contains the table you want. 
# actual_data = data[1]

# # Look up online the rename column function to change the column name to avg temperature.


# # THE EXTRA TASK IS VERY VERY CHALLENGING. But if you want to try it...

# # Use this to merge the datasets. (KEEP IN MIND, THE ASTERIX by country will need to be removed by custom function.)
# df1 = df1.merge(df2, left_on = "product_id", right_on= "product_id", how = "left")

<h4><b>6. Simple merging:</b> Download <u><b>coffee_sales.csv</b></u> and <b><u>temperatures_fixed.csv</u></b> from Moodle.<b></h4>
<p>Use merging to combine these files into one DataFrame, containing the coffee sales data and the corresponding temperature –data. (merge(), see materials for examples)</p>

<span style="color: red;"><b>Use left join, and coffee sales as the first DataFrame!</b></span>

In [82]:
# loading the coffee sales csv with the help of pandas module.

df = pd.read_csv('coffee_sales.csv')
df.head(6)

        Date  Sales  Target_sales  Total_expenses
0  1.10.2012    122            90              76
1  1.10.2012    123            90              45
2  2.10.2012    107            90              36
3  3.10.2012     94           100              21
4  4.10.2012    182            80              54
5  5.10.2012     43            60              12

In [83]:
# loading the temperatures_fixed.csv sales csv with the help of pandas module.


df_1 = pd.read_csv('temperatures_fixed.csv')
df_1.head(6)

       Date  Temperature (C)
0  1.1.2006         4.075000
1  1.1.2007         3.806713
2  1.1.2008        -5.663194
3  1.1.2009        -4.850926
4  1.1.2010         7.807407
5  1.1.2011        -5.585648

In [84]:
# merging the temperatures_fixed.csv named as df_1 and coffee sales.csv named as df from the left

result = pd.merge(df, df_1, how='left')
result

           Date  Sales  Target_sales  Total_expenses  Temperature (C)
0     1.10.2012    122            90              76        19.822917
1     1.10.2012    123            90              45        19.822917
2     2.10.2012    107            90              36        19.020602
3     3.10.2012     94           100              21        15.820139
4     4.10.2012    182            80              54        15.110648
...         ...    ...           ...             ...              ...
1057  23.8.2015    534           360              94        18.253009
1058  24.8.2015    236           160              60        21.114583
1059  25.8.2015     33             0             145        22.575000
1060  26.8.2015    341           230              65        20.204398
1061  27.8.2015     48            30              40        23.113194

[1062 rows x 5 columns]

<b>Extra task: </b> Do the same but with <b>temperatures_unfixed.csv</b> instead. Remember <b>groupby()</b> before attempting merging! 

<b>Also, you might want to remove some of the columns before grouping data => <span style="color: red;">Summary + Hour</span>. </b>

<span><i>You can also try to merge the DataFrames so that the Summary –of the weather is also added. For this, you probably need to figure out first how to determine the "average" Summary for each day (extra challenge!).</i></span>

In [85]:
# extra task code here, if done

unfixed_csv = pd.read_csv('temperatures_unfixed.csv')
unfixed_csv

             Summary  Temperature (C)       Date  Hour
0      Partly Cloudy         9.472222  31.3.2006    22
1      Partly Cloudy         9.355556  31.3.2006    23
2      Mostly Cloudy         9.377778   1.4.2006     0
3      Partly Cloudy         8.288889   1.4.2006     1
4      Partly Cloudy         9.222222   1.4.2006     3
...              ...              ...        ...   ...
96443  Partly Cloudy        26.016667   9.9.2016    17
96444  Partly Cloudy        24.583333   9.9.2016    18
96445  Partly Cloudy        22.038889   9.9.2016    19
96446  Partly Cloudy        21.522222   9.9.2016    20
96447  Partly Cloudy        20.438889   9.9.2016    21

[96448 rows x 4 columns]

In [86]:

df_delelting = unfixed_csv.drop(['Summary','Hour'], axis=1)
df_delelting

       Temperature (C)       Date
0             9.472222  31.3.2006
1             9.355556  31.3.2006
2             9.377778   1.4.2006
3             8.288889   1.4.2006
4             9.222222   1.4.2006
...                ...        ...
96443        26.016667   9.9.2016
96444        24.583333   9.9.2016
96445        22.038889   9.9.2016
96446        21.522222   9.9.2016
96447        20.438889   9.9.2016

[96448 rows x 2 columns]

In [87]:
# merging the temperatures_fixed.csv named as df_1 and coffee sales.csv named as df from the left

result = pd.merge(df, df_delelting, how='left')
result

            Date  Sales  Target_sales  Total_expenses  Temperature (C)
0      1.10.2012    122            90              76        17.211111
1      1.10.2012    122            90              76        17.172222
2      1.10.2012    122            90              76        16.644444
3      1.10.2012    122            90              76        16.127778
4      1.10.2012    122            90              76        16.066667
...          ...    ...           ...             ...              ...
25480  27.8.2015     48            30              40        22.127778
25481  27.8.2015     48            30              40        21.066667
25482  27.8.2015     48            30              40        21.161111
25483  27.8.2015     48            30              40        18.355556
25484  27.8.2015     48            30              40        19.327778

[25485 rows x 5 columns]

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex56coffee.jpg" width="450" />


<h2><b>Advanced extra tasks for extra points (varying challenges, some require Googling):</b></h2>

<h2><b style="color: red;">Co-operate with another student: Jeremy  </b></h2>

<ul>
<li><b>1. Download the "complex.json" –file from Moodle.</b> Note that this data is fairly complex (i.e. heavily nested). Use json_normalize and other needed methods to convert this data into a workable DataFrame.</li>
</ul>

In [88]:
# code for the advanced extra task
json_file = open("complex.json")
response_raw = json_file.read()
json_file.close()
response = json.loads(response_raw)

data = pd.json_normalize(response)
data

,id,brand,model,year,price,ownership.company,ownership.acquired,ownership.payment_info.credit_card,ownership.payment_info.iban
0,1,Ford,F250,1997,72213,Johns and Sons,24/10/2017,jcb,SA47 315V KYTA 8FVT NCGN MM7G
1,2,Dodge,Grand Caravan,1999,42370,"Crist, Hyatt and Leannon",7/6/2020,instapayment,FR74 8157 1767 53I2 VRAN ZMIB U11
2,3,Audi,A5,2011,19191,Bosco and Sons,23/11/2018,jcb,LB32 4989 VCVZ S5BZ X2CT JKG3 QRAW
3,4,Hyundai,Veracruz,2012,21956,Haley Inc,5/6/2016,bankcard,BE62 4961 0596 5774
4,5,Chevrolet,TrailBlazer,2009,53066,"Zulauf, Nolan and Franecki",14/1/2021,jcb,FR11 1768 5506 10IU QVPN XU2H O88
...,...,...,...,...,...,...,...,...,...
95,96,Hyundai,Elantra,1997,38400,Keebler and Sons,26/6/2019,visa-electron,RS34 1571 2547 8662 4201 18
96,97,Mercury,Grand Marquis,1996,27284,Wunsch-Ernser,9/11/2019,mastercard,AD85 4944 9836 X0YY JZAF NIXH
97,98,GMC,Safari,1996,17723,Ondricka-Schuster,17/7/2016,jcb,FR22 8203 4892 75GI 8YFM NAXR B47
98,99,Dodge,Ram Van 1500,2000,32892,Heathcote-Gleichner,21/4/2016,jcb,SA43 49ZA FH7V 20XN BYDW ROEX
99,100,Kia,Sorento,2004,51338,Maggio-O'Connell,12/2/2019,switch,AT13 3843 5698 8421 0247

<ul>
<li><b>2. Load the "simple.json" –file without pandas, and try to get the average price with plain Python. <b>(DON'T USE AI HERE)</b></li>
</ul>

In [89]:
# opening the file and reading
df = open("simple.json", "r")

data = df.read()

# using eval here because json is like an dictionary 
cars = eval(data)

# then i am calculating the sum of all cars prices
total_price = 0
for car in cars:
    total_price += car["price"]

# then after i will divide by the number of cars
average_price = total_price / len(cars)

# then the final step-> print the result
print("The average price is:", average_price)

# and on the end close the opened simple.json file
df.close()

The average price is: 42373.86

<ul>
<li><b>3. Download the "complex.xml" file from Moodle, and create a DataFrame out of it.</b></li>
<ul>
    <li><b>Note:</b> using pandas.read_xml() would otherwise work, but it ignores the "ownership" –field. You'll have to find another way to get this data into your DataFrame as well!</li>
</ul>
</ul>

In [90]:
# code for the advanced extra task, you can also create a separate notebook for this 
# (might be a better idea, since a new dataset always adds quite much new code)

<ul>
    <li><b>4. Try out Selenium on a site that cannot be scraped with traditional methods. You can use this tutorial as the starting point:</b></li>
    <ul>
        <li><a href="https://www.toptal.com/python/web-scraping-with-python">https://www.toptal.com/python/web-scraping-with-python</a></li>
    </ul>
</ul>

In [91]:
# code for the advanced extra task, you can also create a separate notebook for this 
# (might be a better idea, since a new dataset always adds quite much new code)

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_5/ex5charts.jpg" width="600" />

<b>5. Extra challenging advanced task: <span style="color: red;">integrating data sources</span></b>

<ul>
<li><b>Integrate two or more datasets into one matching dataset (pandas DataFrame), but use any datasets you can find in Kaggle.com instead of the previous coffee sales + temperature -datasets</b></li>
<br />
<ul>
<li>Find two or more datasets (Kaggle.com etc.) that have something in common and can be used for merging. </li>
</ul>

<br />
<ul>
<li><b>Typical common columns:</b></li>
<ul>
<li>Coordinates (lat/lng etc.)</li>
<li>Years, months</li>
<li>reference ids (e.g. product id -> product data)</li>
</ul>
</ul>

<br />
<ul>
<li><b>You can use pandas.merge() in order to combine DataFrames</b></li>
<ul>
<li>When combining DataFrames, make sure that the merge doesn’t mess up your data</li>
<li><b>Note:</b> merge can often create way too many extra rows depending on the merging parameters</li>

</ul>
</ul>

<br />
<ul>
<li><b>This exercise can provide even large amounts of points, depending on difficulty. Aspects that affect grading:</b></li>
<ul>
<li>Amount of datasets</li>
<li>Difficulty of the datasets</li>
<li>Using different data formats all at once (XML, JSON, CSV etc.)</li>
<li>Other techniques used to add data: web scraping, data APIs etc.</li>
</ul>
</ul>


</ul>

In [92]:
# this exercise is probably better to do in a separate Jupyter notebook